import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "../trpc/provider";
import { SessionProvider } from "../components/providers/SessionProvider";
import { AuthProvider } from "../components/providers/AuthProvider";
import { SupabaseProvider } from "../components/providers/supabase-provider";
import { UserSyncProvider } from "../components/providers/UserSyncProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCProvider>
          <SupabaseProvider>
            <UserSyncProvider>
              <SessionProvider>
                <AuthProvider>{children}</AuthProvider>
              </SessionProvider>
            </UserSyncProvider>
          </SupabaseProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
